name: webviewx
description: A feature-rich cross-platform webview using webview_flutter for
  mobile and iframe for web. JS interop-ready.
homepage: https://github.com/adrianflutur/webviewx
version: 4.9.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  path: ^1.9.0
  pointer_interceptor: ^0.10.1+2
  uuid: ^4.5.1
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
